version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
    day: sunday
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    day: sunday
- package-ecosystem: npm
  directory: "/ui-tests"
  schedule:
    interval: monthly
    day: sunday
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
    day: sunday
