language: python

python:
  - 3.6
  - 3.7
  - 3.8

before_install:
  - nvm install 13
  - pip install poetry

install:
  - poetry install
  - poetry run jupyter nbextension install vega --py --sys-prefix
  - yarn

script:
  - yarn lint
  - poetry run pytest vega

cache: yarn
