language: python

python:
  - 3.6
  - 3.7
  - 3.8

before_install:
  - pip install poetry

install:
  - poetry install
  - poetry shell
  - jupyter nbextension install vega --py --sys-prefix
  - yarn

script:
  - yarn lint
  - pytest vega

cache: yarn
