language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

env:
  - DEPS="pandas jupyter pytest"

install:
  - conda create -n testenv --yes python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - conda install --yes $DEPS
  - python setup.py install
  - jupyter nbextension install vega --py --sys-prefix
  - yarn

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda

script:
  - yarn lint
  - py.test vega

cache: yarn
