name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: ["3.6", "3.7", "3.8", "3.9"]

    name: Python ${{ matrix.python }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2.3.1
        with:
          python-version: ${{ matrix.python }}

      - name: Setup poetry
        uses: abatilo/actions-poetry@v2.1.4
        with:
          poetry-version: 1.1.12

      - name: Configure poetry
        run: poetry config virtualenvs.in-project true

      - name: Install Python dependencies
        run: poetry install

      - run: poetry run jupyter nbextension install vega --py --sys-prefix

      - name: Setup Node
        uses: actions/setup-node@v2.5.1

      - name: Install Node dependencies
        run: yarn --frozen-lockfile

      - name: Lint TypeScript
        run: yarn lint

      - name: Build JavaScript
        run: yarn build

      - name: Run pytest
        run: poetry run pytest vega
