name: UI Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11"]

    name: Python ${{ matrix.python }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Setup poetry
        uses: abatilo/actions-poetry@v2.3.0
        with:
          poetry-version: 1.3.2

      - name: Configure poetry
        run: poetry config virtualenvs.create false

      - name: Install Python dependencies
        run: |
          poetry install
          python -m pip install jupyterlab==3.6.1

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install Node dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn run build

      - name: Setup and start Jupyterlab
        run: |
          jupyter labextension install .
          jupyter labextension disable "@jupyterlab/apputils-extension:announcements"
          cd ui-tests/
          yarn --frozen-lockfile
          yarn playwright install chromium
          yarn start:detached
      - name: Wait for JupyterLab
        uses: ifaxity/wait-on-action@v1
        with:
          resource: http-get://localhost:8888/api
          timeout: 20000  
      - name: Run tests
        run: |
          cd ui-tests/
          yarn run test
      - name: Update images
        if: failure()
        run: |
          cd ui-tests/
          yarn run test:update
      - name: Upload images
        if: failure()    
        uses: actions/upload-artifact@v3
        with:
          name: ipyvega-updated-snapshots
          path: ui-tests/tests/vega.test.ts-snapshots/